"""Event handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/090_callbacks.ipynb.

# %% auto #0
__all__ = ['CALLBACK_BACKENDS', 'GradientAccumulation', 'EarlyStoppingCallback', 'SaveModelCallback', 'ReduceLROnPlateau',
           'CSVLogger', 'ParamScheduler', 'SchedCos', 'SchedExp', 'SchedLin', 'SchedNo', 'BioCallback',
           'register_callback_backend', 'get_callback_backend', 'CallbackBackend', 'FastaiCallbackBackend',
           'MonaiCallbackBackend', 'MeanLossGraphCallback', 'ShowGraphCallback']

# %% ../nbs/090_callbacks.ipynb #5f3a7bf7
# ---------------------------------------------------------------------
# Standard library
# ---------------------------------------------------------------------
from abc import ABC, abstractmethod
from contextlib import nullcontext
from typing import Any, Callable, Dict, Optional, Type

# ---------------------------------------------------------------------
# Third-party
# ---------------------------------------------------------------------
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------
# fastai
# ---------------------------------------------------------------------
from fastai.callback.core import Callback as FastaiCallback, Tensor, range_of
from fastai.callback.schedule import ParamScheduler, SchedCos, SchedExp, SchedLin, SchedNo
from fastai.callback.tracker import (
    EarlyStoppingCallback,
    ReduceLROnPlateau,
    SaveModelCallback,
    ShowGraphCallback as FastaiShowGraphCallback,
)
from fastai.callback.training import GradientAccumulation, ShortEpochCallback
from fastai.vision.all import CSVLogger
# from fastprogress.fastprogress import master_bar, NBProgressBar

# ---------------------------------------------------------------------
# BONSAI
# ---------------------------------------------------------------------
from .backend import get_backend
from .utils import *
from .visualize import bonsai_style, colorlist, plot_metrics


# %% ../nbs/090_callbacks.ipynb #703f9a6d
class BioCallback:
    """
    Backend-independent interface for callbacks in bonsai.

    ``BioCallback`` provides a common interface for callbacks implemented
    across different deep-learning backends. A callback can define a
    backend-specific implementation through attributes such as ``_monai``,
    ``_fastai``, or ``_ignite``. If no implementation is defined for the
    active backend, ``_default`` is used instead.

    The active backend is selected globally with
    :func:`bonsai.set_backend` and is obtained through
    :func:`bonsai.get_backend`. Consequently, callbacks do not expose a
    ``backend`` argument.

    Attributes
    ----------
    _default : callable, optional
        Default callback implementation used when no backend-specific
        implementation is available.
    _<backend> : callable, optional
        Backend-specific callback implementation. For example, ``_monai``
        or ``_fastai``. When defined, it takes precedence over
        ``_default`` for the corresponding active backend.

    Examples
    --------
    Select the backend globally and instantiate callbacks normally:

    >>> bonsai.set_backend("monai")
    >>> callback = CSVLogger()

    The same callback interface can then be used with another backend:

    >>> bonsai.set_backend("fastai")
    >>> callback = CSVLogger()
    """

    _default = None

    @classmethod
    def _get_callback(cls, backend):
        """
        Return the callback implementation for a registered backend.
        """
        if backend not in CALLBACK_BACKENDS:
            raise ValueError(
                f"Unknown callback backend '{backend}'. "
                f"Available callback backends: {list(CALLBACK_BACKENDS)}"
            )

        callback_cls = getattr(cls, f"_{backend}", None)
        if callback_cls is None:
            callback_cls = cls._default

        if callback_cls is None:
            raise ValueError(
                f"No callback implementation for backend '{backend}' "
                f"and no default implementation is defined for "
                f"{cls.__name__}."
            )

        return callback_cls

    @classmethod
    def _create_callback(cls, backend, *args, **kwargs):
        """
        Create the callback using the selected backend adapter.
        """
        callback_cls = cls._get_callback(backend)
        backend_cls = CALLBACK_BACKENDS[backend]

        return backend_cls().create(
            callback_cls,
            *args,
            **kwargs,
        )

    def __new__(cls, *args, **kwargs):
        """
        Instantiate the callback using the globally active backend.
        """
        backend = get_backend()

        return cls._create_callback(
            backend,
            *args,
            **kwargs,
        )

# %% ../nbs/090_callbacks.ipynb #e817202c
CALLBACK_BACKENDS: Dict[str, Type["CallbackBackend"]] = {}


def register_callback_backend(name: str):
    """
    Register a callback backend adapter.

    Parameters
    ----------
    name : str
        Name of the backend.
    """
    name = name.lower()

    def decorator(cls):
        if name in CALLBACK_BACKENDS:
            raise ValueError(
                f"Callback backend '{name}' is already registered."
            )

        CALLBACK_BACKENDS[name] = cls
        cls.name = name

        return cls

    return decorator


def get_callback_backend(name: Optional[str] = None) -> "CallbackBackend":
    """
    Return the registered callback backend adapter.

    Parameters
    ----------
    name : str, optional
        Backend name. If ``None``, the globally active backend returned by
        :func:`bonsai.get_backend` is used.

    Returns
    -------
    CallbackBackend
        Registered callback backend adapter.

    Raises
    ------
    ValueError
        If the requested backend is not registered.
    """
    backend = (name or get_backend()).lower()

    if backend not in CALLBACK_BACKENDS:
        raise ValueError(
            f"Unknown callback backend '{backend}'. "
            f"Available callback backends: {list(CALLBACK_BACKENDS)}"
        )

    return CALLBACK_BACKENDS[backend]()

# %% ../nbs/090_callbacks.ipynb #24e9ad14
class CallbackBackend(ABC):
    """
    Adapter for constructing backend-native callbacks.
    """

    name: str

    @classmethod
    def create(
        cls,
        callback: Any,
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        """
        Construct a backend-native callback.
        """
        if isinstance(callback, BioCallback):
            return callback._create(*args, **kwargs)

        if isinstance(callback, type):
            return callback(*args, **kwargs)

        if callable(callback) and args == () and kwargs == {}:
            return callback

        return callback

# %% ../nbs/090_callbacks.ipynb #5ea7cd9d
@register_callback_backend("fastai")
class FastaiCallbackBackend(CallbackBackend):
    """
    Fastai callback backend.
    """

    @classmethod
    def create(
        cls,
        callback: Any,
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        if isinstance(callback, BioCallback):
            return callback._create(*args, **kwargs)

        if isinstance(callback, type):
            return callback(*args, **kwargs)

        return callback

# %% ../nbs/090_callbacks.ipynb #30e7a4dc
@register_callback_backend("monai")
class MonaiCallbackBackend(CallbackBackend):
    """
    MONAI callback backend.

    MONAI callbacks are generally represented by event handlers.
    """

    @classmethod
    def create(
        cls,
        callback: Any,
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        if isinstance(callback, BioCallback):
            return callback._create(*args, **kwargs)

        if isinstance(callback, type):
            return callback(*args, **kwargs)

        return callback

# %% ../nbs/090_callbacks.ipynb #88f67398
GradientAccumulation = GradientAccumulation

# %% ../nbs/090_callbacks.ipynb #add0cb27
EarlyStoppingCallback = EarlyStoppingCallback

# %% ../nbs/090_callbacks.ipynb #4b764f8f
SaveModelCallback = SaveModelCallback

# %% ../nbs/090_callbacks.ipynb #1b5eb715
ReduceLROnPlateau = ReduceLROnPlateau

# %% ../nbs/090_callbacks.ipynb #10a3161f
class MeanLossGraphCallback(FastaiCallback):
    "Update a graph of training and validation loss"
    order,run_valid=65,False

    def __init__(self, *args, style=bonsai_style, minimize_metrics=False, orientation="vertical", **kwargs):
        super().__init__(*args, **kwargs)
        self.style = style
        self.minimize_metrics = minimize_metrics
        self.orientation = orientation

    def before_fit(self):
        self.run = not hasattr(self.learn, 'lr_finder') and not hasattr(self, "gather_preds")
        if not(self.run): return
        self.nb_batches = []
        self.train_losses = []
        assert hasattr(self.learn, 'progress')

    def after_train(self): 
        self.nb_batches.append(self.train_iter)

    def after_epoch(self):
        "Plot validation loss in the pbar graph"
        if not self.nb_batches: return
        rec = self.learn.recorder
        epochs = range(0, len(self.nb_batches))
        self.train_losses.append(rec.log[1])
        val_losses = [v[1] for v in rec.values]
        
        x_bounds = (0, self.n_epoch - 1)
        y_bounds = (0, max((max(Tensor(rec.losses)), max(Tensor(val_losses)))))
        ctx = plt.rc_context(self.style) if self.style else nullcontext()
        with ctx:
            self.progress.mbar.update_graph([(epochs, self.train_losses), (epochs, val_losses)], x_bounds, y_bounds)

    def after_fit(self):
        if not self.run:
            return
        
        plot_metrics(self.learn,
                     style=self.style,
                     minimize_metrics=self.minimize_metrics,
                     orientation=self.orientation,
        )


# %% ../nbs/090_callbacks.ipynb #2034a7da
class ShowGraphCallback(FastaiShowGraphCallback):

    def __init__(self, *args, style=bonsai_style, **kwargs):
        super().__init__(*args, **kwargs)
        self.style = style

    def __call__(self, *args, **kwargs):

        ctx = plt.rc_context(self.style) if self.style else nullcontext()

        with ctx:
            return super().__call__(*args, **kwargs)

# %% ../nbs/090_callbacks.ipynb #30b9de34
CSVLogger = CSVLogger

# %% ../nbs/090_callbacks.ipynb #ece6d669
ParamScheduler = ParamScheduler

# %% ../nbs/090_callbacks.ipynb #5005aa8b
SchedCos = SchedCos

# %% ../nbs/090_callbacks.ipynb #f9000aa6
SchedExp = SchedExp

# %% ../nbs/090_callbacks.ipynb #d7ee6740
SchedLin = SchedLin

# %% ../nbs/090_callbacks.ipynb #470aeb80
SchedNo = SchedNo
