"""Event handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/090_callbacks.ipynb.

# %% auto #0
__all__ = ['GradientAccumulation', 'EarlyStoppingCallback', 'SaveModelCallback', 'ReduceLROnPlateau', 'CSVLogger',
           'ParamScheduler', 'SchedCos', 'SchedExp', 'SchedLin', 'SchedNo', 'MeanLossGraphCallback',
           'ShowGraphCallback']

# %% ../nbs/090_callbacks.ipynb #5f3a7bf7
from fastai.callback.training import ShortEpochCallback, GradientAccumulation
from fastai.callback.tracker import  EarlyStoppingCallback, SaveModelCallback, ReduceLROnPlateau, ShowGraphCallback as FastaiShowGraphCallback
from fastai.callback.schedule import ParamScheduler, SchedCos, SchedExp, SchedLin, SchedNo
from fastai.callback.core import Callback as fastaiCallback, range_of, Tensor
from fastai.vision.all import CSVLogger
import matplotlib.pyplot as plt
from contextlib import nullcontext

from .visualize import bonsai_style, colorlist
from .backend import get_backend
from .utils import *


# %% ../nbs/090_callbacks.ipynb #80514f91
class MeanLossGraphCallback(fastaiCallback):
    "Update a graph of training and validation loss"
    order,run_valid=65,False

    def __init__(self, *args, style=bonsai_style, **kwargs):
        super().__init__(*args, **kwargs)
        self.style = style

    def before_fit(self):
        self.run = not hasattr(self.learn, 'lr_finder') and not hasattr(self, "gather_preds")
        if not(self.run): return
        self.nb_batches = []
        self.train_losses = []
        assert hasattr(self.learn, 'progress')

    def after_train(self): 
        self.nb_batches.append(self.train_iter)

    def after_epoch(self):
        "Plot validation loss in the pbar graph"
        if not self.nb_batches: return
        rec = self.learn.recorder
        epochs = range(0, len(self.nb_batches))
        self.train_losses.append(rec.log[1])
        val_losses = [v[1] for v in rec.values]
        x_bounds = (0, self.n_epoch - 1)
        y_bounds = (0, max((max(Tensor(rec.losses)), max(Tensor(val_losses)))))
        ctx = plt.rc_context(self.style) if self.style else nullcontext()
        with ctx:
            self.progress.mbar.update_graph([(epochs, self.train_losses), (epochs, val_losses)], x_bounds, y_bounds)


# %% ../nbs/090_callbacks.ipynb #88f67398
GradientAccumulation = GradientAccumulation

# %% ../nbs/090_callbacks.ipynb #add0cb27
EarlyStoppingCallback = EarlyStoppingCallback

# %% ../nbs/090_callbacks.ipynb #4b764f8f
SaveModelCallback = SaveModelCallback

# %% ../nbs/090_callbacks.ipynb #1b5eb715
ReduceLROnPlateau = ReduceLROnPlateau

# %% ../nbs/090_callbacks.ipynb #fc3c851b
class ShowGraphCallback(FastaiShowGraphCallback):

    def __init__(self, *args, style=bonsai_style, **kwargs):
        super().__init__(*args, **kwargs)
        self.style = style

    def __call__(self, *args, **kwargs):

        ctx = plt.rc_context(self.style) if self.style else nullcontext()

        with ctx:
            return super().__call__(*args, **kwargs)

# %% ../nbs/090_callbacks.ipynb #30b9de34
CSVLogger = CSVLogger

# %% ../nbs/090_callbacks.ipynb #ece6d669
ParamScheduler = ParamScheduler

# %% ../nbs/090_callbacks.ipynb #5005aa8b
SchedCos = SchedCos

# %% ../nbs/090_callbacks.ipynb #f9000aa6
SchedExp = SchedExp

# %% ../nbs/090_callbacks.ipynb #d7ee6740
SchedLin = SchedLin

# %% ../nbs/090_callbacks.ipynb #470aeb80
SchedNo = SchedNo
