"""Universal image loaders and readers for bonsai, fully compatible with the standard MONAI ecosystem."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/010_io.ipynb.

# %% auto #0
__all__ = ['ScalarImage', 'SaveImage', 'SaveImaged', 'LOADER_REGISTRY', 'LoadImage', 'LoadImaged', 'tiff2torch', 'string2dict',
           'split_path', 'is_ome_tiff', 'BioImageMetadata', 'get_aics_metadata', 'extract_formats', 'bioio_loader',
           'split_hdf_path', 'hdf5_loader', 'LoaderRegistry', 'image_reader', 'image_reader_dict', 'BioImageReader']

# %% ../nbs/010_io.ipynb #58b60095
# =================================
# Standard library
# =================================
import time
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from google_crc32c import value

# =================================
# Scientific / data
# =================================
import h5py
import numpy as np
import xarray as xr

# =================================
# Bioimage IO
# =================================
from bioio import BioImage as AICSImage
from bioio import Writer as writer
from bioio_tifffile import Reader as TiffReader
from bioio_ome_tiff import Reader as OmeTiffReader
from bioio_czi import Reader as CziReader
from bioio_imageio import Reader as IOReader

# =================================
# Medical imaging
# =================================
from torchio import ScalarImage

# =================================
# fastai
# =================================
from fastai.data.all import *
from fastai.vision.all import *

# =================================
# MONAI
# =================================
from monai.transforms import LoadImage, LoadImaged, SaveImage, SaveImaged
from monai.data.image_reader import ImageReader
from collections.abc import Callable, Iterable, Sequence
from monai.config import PathLike
from monai.data import MetaTensor
from monai.data.utils import is_supported_format
from monai.utils import MetaKeys

# =================================
# bonsai
# =================================
from .utils import *


# %% ../nbs/010_io.ipynb #8a6181f6
ScalarImage = ScalarImage

# %% ../nbs/010_io.ipynb #f820309d
SaveImage = SaveImage
SaveImaged = SaveImaged

# %% ../nbs/010_io.ipynb #c87d4d38
def tiff2torch(file_path: str):
    '''
    Load tiff into pytorch tensor
    '''
    import tifffile as tiff
    
    img = np.array(tiff.imread(file_path))
    return torch_from_numpy(img)

# %% ../nbs/010_io.ipynb #9c768b4a
def string2dict(s: str) -> dict[str, int | slice | None]:
    """
    Parse layout strings with:
        - sizes: C2
        - slices: Y[100:200]
        - steps:  Y[100:200:2]

    Returns:
        dict[str, int | slice | None]
    """

    result = {}

    pattern = re.findall(
        r"([A-Za-z])"               # axis
        r"(\d+)?"                   # optional size
        r"(?:\[(\d*):(\d*):?(\d*)\])?",  # optional slice w/ step
        s
    )

    for axis, size, start, stop, step in pattern:
        axis = axis.upper()

        # -------------------------
        # slice case
        # -------------------------
        if start or stop or step:
            slc = slice(
                int(start) if start else None,
                int(stop) if stop else None,
                int(step) if step else None,
            )
            result[axis] = slc

        # -------------------------
        # size case
        # -------------------------
        elif size:
            result[axis] = int(size)

        # -------------------------
        # empty axis
        # -------------------------
        else:
            result[axis] = None

    return result

# %% ../nbs/010_io.ipynb #f111048c
def split_path(file_path, # The path to the file to split
                   exts:(L, list)=['.ome.tiff', '.tiff', '.tif', '.png'] # List of filename extensions 
                   ):
    img_ext = [ext for ext in exts if ext in file_path]
    if img_ext == []:
        return file_path, dict()
    p = file_path.split(img_ext[0])
    if len(p) == 1 or p[1] == '':
        return file_path, dict()
    else:
        path = p[0] + img_ext[0]
        ind_dict = string2dict(p[1])
    return path, ind_dict

# %% ../nbs/010_io.ipynb #3f4aac4a
def is_ome_tiff(path: Path) -> bool:
    return path.suffixes[-2:] == [".ome", ".tiff"]

# %% ../nbs/010_io.ipynb #646c32a6
def _to_serializable(value):
    """
    Expand metadata-like objects into dictionaries recursively.
    """
    if isinstance(value, BioImageMetadata):
        return value.to_dict()

    # numpy scalar types
    if isinstance(value, np.generic):
        return value.item()
    
    # primitives
    if isinstance(value, (str, int, float, bool, type(None))):
        return value

    # arrays
    if isinstance(value, (np.ndarray, xr.DataArray)):
        return "<array skipped>"

    # dicts
    if isinstance(value, dict):
        return {
            k: _to_serializable(v)
            for k, v in value.items()
        }

    # lists / tuples
    if isinstance(value, (list, tuple)):
        return [_to_serializable(v) for v in value]

    # objects with __dict__
    if hasattr(value, "__dict__"):
        return {
            k: _to_serializable(v)
            for k, v in vars(value).items()
            if not k.startswith("_")
        }

    # attrs/dataclass-like objects
    if hasattr(value, "__slots__"):
        return {
            k: _to_serializable(getattr(value, k))
            for k in value.__slots__
            if hasattr(value, k)
        }

    # fallback
    return str(value)


def _safe_attr(obj, attr, default=None):
    try:
        return getattr(obj, attr)
    except Exception:
        return default


@dataclass(slots=True)
class BioImageMetadata:
    """
    Lightweight metadata summary for BioIO-backed images.
    """
    filepath: str | None = None
    reader: str | None = None
    dims: str | None = None
    source_shape: tuple[int, ...] | None = None
    dtype: str | None = None
    physical_pixel_sizes: dict | None = None
    scenes: tuple[str, ...] | None = None
    current_scene: str | None = None
    channel_names: tuple[str, ...] | None = None
    layout: str | None = None
    standard_fields: dict = field(default_factory=dict)
    raw: dict = field(default_factory=dict)

    @classmethod
    def from_bioimage(cls, image, path=None, layout=None, raw=None):
        shape = _safe_attr(image, "shape")
        scenes = _safe_attr(image, "scenes")
        channel_names = _safe_attr(image, "channel_names")
        physical_pixel_sizes = _safe_attr(image, "physical_pixel_sizes")
        standard_metadata = _to_serializable(_safe_attr(image, "standard_metadata"))
        reader = _safe_attr(image, "reader")

        return cls(
            filepath=None if path is None else str(path),
            reader=None if reader is None else reader.__class__.__name__,
            dims=str(_safe_attr(image, "dims")),
            source_shape=None if shape is None else tuple(int(v) for v in shape),
            dtype=str(_safe_attr(image, "dtype")),
            physical_pixel_sizes=_to_serializable(physical_pixel_sizes),
            scenes=None if scenes is None else tuple(str(s) for s in scenes),
            current_scene=_to_serializable(_safe_attr(image, "current_scene")),
            channel_names=None if channel_names is None else tuple(str(c) for c in channel_names),
            layout=layout,
            standard_fields={} if not isinstance(standard_metadata, dict) else standard_metadata,
            raw={} if raw is None else raw,
        )

    def to_dict(self, include_raw: bool = False) -> dict:
        meta = asdict(self)
        raw = meta.pop("raw", {})
        standard_fields = meta.pop("standard_fields", {})
        meta = {
            k: _to_serializable(v)
            for k, v in meta.items()
            if v is not None
        }
        meta.update({
            k: _to_serializable(v)
            for k, v in standard_fields.items()
            if v is not None and k not in meta
        })
        if include_raw and raw:
            meta["bioio"] = _to_serializable(raw)
        return meta


def get_aics_metadata(obj, skip=None):
    """
    Return expanded metadata dictionary from an AICSImage object.

    This is intentionally opt-in because walking all BioIO attributes can force
    expensive lazy properties. Use BioImageMetadata for the fast default path.
    """

    default_skip = {
        "data",
        "dask_data",
        "xarray_data",
        "xarray_dask_data",
    }

    if skip is not None:
        default_skip.update(skip)

    attrs = {}

    for attr in dir(obj):

        if attr.startswith("_"):
            continue

        if attr in default_skip:
            continue

        try:
            value = getattr(obj, attr)

            # skip methods/functions
            if callable(value):
                continue

            attrs[attr] = _to_serializable(value)

        except Exception as e:
            attrs[attr] = f"<error: {e}>"

    return attrs


def _bioio_metadata(image, path=None, layout=None, metadata="summary", skip=None):
    """
    Build BioIO metadata without forcing expensive lazy attributes by default.
    """
    if metadata in (False, None, "none"):
        return {}

    if isinstance(metadata, BioImageMetadata):
        return metadata.to_dict()

    if metadata in (True, "full"):
        raw = get_aics_metadata(image, skip=skip)
        return BioImageMetadata.from_bioimage(
            image,
            path=path,
            layout=layout,
            raw=raw,
        ).to_dict(include_raw=True)

    return BioImageMetadata.from_bioimage(
        image,
        path=path,
        layout=layout,
    ).to_dict()


# %% ../nbs/010_io.ipynb #0ae336ba
def extract_formats(filenames: Sequence[str] | str) -> list[str | None]:
    """
    Extract file format(s) from one or multiple filenames.

    Supports:
        - standard extensions (.nii.gz, .png, .npz)
        - HDF5 internal paths (.hdf5/... or .h5/...)

    Args:
        filenames: single path or sequence of paths.

    Returns:
        List of format strings in uppercase (without dots),
        or None if no suffix is found.
    """

    if isinstance(filenames, (str, Path)):
        filenames = [filenames]

    formats = []

    for name in filenames:
        path_str = str(name).lower()

        # HDF5 special case
        if any(ext in path_str for ext in (".h5", ".hdf5")):
            formats.append("HDF5")
            continue

        # Standard suffixes
        suffixes = Path(name).suffixes
        if suffixes:
            fmt = "".join(suffixes).lstrip(".").upper()
            formats.append(fmt)
        else:
            formats.append(None)

    return formats

# %% ../nbs/010_io.ipynb #3a3cad7c
def _sanitize(obj):
    """
    Convert non-serializable objects into safe representations
    and recursively extract nested transform parameters.
    """

    # dictionaries
    if isinstance(obj, dict):
        return {k: _sanitize(v) for k, v in obj.items()}

    # lists / tuples
    elif isinstance(obj, (list, tuple)):
        return type(obj)(_sanitize(v) for v in obj)

    # classes/types
    elif isinstance(obj, type):
        return obj.__name__

    # numpy dtypes
    elif isinstance(obj, np.dtype):
        return str(obj)

    # nested objects / transforms
    elif hasattr(obj, "__dict__") and not isinstance(obj, (str, int, float, bool)):
        return {
            "__class__": obj.__class__.__name__,
            **{
                k: _sanitize(v)
                for k, v in vars(obj).items()
                if not k.startswith("_")
            },
        }

    # callables
    elif callable(obj):
        return obj.__name__ if hasattr(obj, "__name__") else str(obj)

    # everything else
    else:
        return obj

# %% ../nbs/010_io.ipynb #e1ba1c73
class bioio_loader():
    
    def __init__(self,
                 ind_dict=None, # Dictionary indicating the channels to load
                 loader=None, # Optional custom reader to use for loading the image
                 channels="CZYX", # The desired channel order for the output data
                 metadata: str | bool | BioImageMetadata = "summary", # Metadata mode: "summary", "full", or "none"
                 metadata_skip: set[str] | None = None, # Extra full-metadata fields to skip
                 **kwargs,
                ):
        store_attr()
        self.kwargs = kwargs

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The file path to the image             
               ):

        """
        Loads an image from the specified path using AICSImage library.

        Parameters:
            path (str): The file path to the image.

        Returns:
            tuple: A tuple containing the image data and its affine transformation matrix.
                The image data is a NumPy array representing the image.
                The affine transformation matrix is a 4x4 NumPy array.
        """

        ind_dict = self.ind_dict
        if ind_dict == None:
            # parse path string
            path, ind_dict = split_path(str(path))
             
        path = str(path)
        self.kwargs.setdefault('reconstruct_mosaic', False)
        image_aics = AICSImage(path, reader=self.loader, **self.kwargs)

        # Convert to numpy array    
        data = image_aics.get_image_data(self.channels, **ind_dict)
        # extract lightweight metadata by default
        meta = _bioio_metadata(
            image_aics,
            path=path,
            layout=self.channels,
            metadata=self.metadata,
            skip=self.metadata_skip,
        )
        # Create an identity affine transformation matrix
        affine = np.eye(4)
        # Return the image data and the affine matrix
        return data, meta, affine



# %% ../nbs/010_io.ipynb #2bf5edc3
def split_hdf_path(file_path, # The path to the HDF5 file to split
                   hdf5_exts:(L, list)=['.h5','.hdf5'] # List of filename extensions 
                   ):
    hdf5_ext = [ext for ext in hdf5_exts if ext in file_path][0]
    if hdf5_ext == []:
        return file_path, None, None
    p = file_path.split(hdf5_ext)
    if len(p) == 1 or p[1] == '':
        return file_path, None, None
    else:
        path = p[0] + hdf5_ext
        tmp = p[1].split('/')[1:]
        dataset = os.path.join(*tmp[:-1])
        patch = tmp[-1]
    return path, dataset, patch

# %% ../nbs/010_io.ipynb #82d62082
class hdf5_loader():
    def __init__(self,
                 dataset: Optional[str]=None, # The dataset to load
                 patch: Optional[str]=None, # The patch to load from the dataset
                 hdf5_exts: List[str]=['.h5','.hdf5'], # List of filename extensions 
                 channels: str="CYX" # The desired channel layout for the output data
                ):
        store_attr()

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The path to the HDF5 file to be read
               ):
        """
        Reads a *.h5 (HDF5 format) file and returns the image data along with an identity affine matrix.

        Parameters:
        path (str): The path to the file to be read.

        Returns:
        tuple: A tuple containing:
            - data (numpy.ndarray): The image data read from the file.
            - affine (numpy.ndarray): A 4x4 identity affine matrix.
        """
        
        # split path
        if self.dataset == None:
            path, dataset, patch = split_hdf_path(path, self.hdf5_exts)
            self.dataset = dataset
            self.patch = patch

        with h5py.File(path, 'r') as file:
                if self.dataset == None: print('List of datasets in this file: \n',list(file.keys())); return None
                else:
                    data = file[self.dataset + '/' + self.patch][:] 
                    meta = dict(file[self.dataset].attrs)
                    if 'patch_location' in file[self.dataset + '/' + self.patch].attrs:
                        meta['patch_location'] = file[self.dataset + '/' + self.patch].attrs['patch_location']

        # adjust data dimensions according to channels layout
        while len(data.shape) < len(self.channels):
            # add absent dimensions assuming missing dimensions are at the beginning
            data = np.expand_dims(data, axis=0)
        if len(data.shape) > len(self.channels):
            # remove absent dimensions assuming that data is in CZYX order and missing dimensions are at the beginning
            data = data[(0,)*(data.ndim - len(self.channels)) + (slice(None),)*len(self.channels)]
                
        # If affine is not in meta dict, create a 4x4 identity affine NumpyArray
        if 'affine' in meta:
            affine = meta['affine']
        else:
            affine = np.eye(4)

        # Return the image data and the affine matrix
        return data, meta, affine


# %% ../nbs/010_io.ipynb #d418d00e
def _as_transform_list(transforms):
    if transforms is None:
        return ()
    if callable(transforms):
        return (transforms,)
    return transforms


def _preprocess(obj, transforms=None):
    transforms = _as_transform_list(transforms)
    meta = obj.meta
    meta['size_loaded'] = obj.shape

    if not transforms:
        meta['size_after_tfms'] = obj.shape
        return obj

    transform_meta = meta.setdefault('transforms', {})

    for t in transforms:
        start = time.perf_counter()
        obj = t(obj)
        elapsed = time.perf_counter() - start

        meta = obj.meta
        if transform_meta is not meta.get('transforms'):
            transform_meta = meta.setdefault('transforms', transform_meta)

        raw_params = getattr(t, "__dict__", None)
        transform_meta[t.__class__.__name__] = {
            'time': elapsed,
            'params': {} if not raw_params else _sanitize(raw_params),
        }

    obj.meta['size_after_tfms'] = getattr(obj, "shape", None)

    return obj


# %% ../nbs/010_io.ipynb #582c31aa
def _preprocess_dict(
    obj: dict,
    transforms: Callable | Iterable[Callable] | None = None,
) -> dict:
    """
    Apply dictionary-based transforms and attach metadata to transformed
    MetaTensor entries.

    This function is designed for MONAI-style dictionary transforms
    (e.g. MapTransform subclasses) that expose a ``keys`` attribute.
    Metadata is stored directly in each transformed MetaTensor under
    ``tensor.meta``.

    Stored metadata includes:
        - ``size_loaded``:
            Shape before preprocessing.
        - ``transforms``:
            Per-transform timing and parameter information.
        - ``size_after_tfms``:
            Final shape after all transforms.

    Args:
        obj:
            Input dictionary containing MetaTensor objects.
        transforms:
            A callable or iterable of callables operating on dictionaries.

    Returns:
        dict:
            Transformed dictionary with updated MetaTensor metadata.
    """
    transforms = _as_transform_list(transforms)
    if not transforms:
        return obj

    processed_keys = set()

    for t in transforms:
        keys = getattr(t, "keys", ())
        name = t.__class__.__name__
        raw_params = getattr(t, "__dict__", None)
        safe_params = {} if not raw_params else _sanitize(raw_params)

        start = time.perf_counter()
        obj = t(obj)
        elapsed = time.perf_counter() - start

        for key in keys:
            tensor = obj.get(key)

            if not isinstance(tensor, MetaTensor):
                continue

            processed_keys.add(key)
            tensor.meta.setdefault("transforms", {})[name] = {
                "time": elapsed,
                "params": safe_params,
            }

    for key in processed_keys:
        tensor = obj[key]

        if isinstance(tensor, MetaTensor):
            tensor.meta["size_after_tfms"] = tensor.shape 

    return obj


# %% ../nbs/010_io.ipynb #c60c74aa
class LoaderRegistry:
    def __init__(self):
        self._loaders = {}

    def register(self, *suffixes):
        def decorator(fn):
            for s in suffixes:
                self._loaders[s.lower()] = fn
            return fn
        return decorator

    def get(self, path: Path):
        full_suffix = "".join(path.suffixes).lower()
        if full_suffix in self._loaders:
            return self._loaders[full_suffix]
        return self._loaders.get(path.suffix.lower())


LOADER_REGISTRY = LoaderRegistry()

# %% ../nbs/010_io.ipynb #22586921
def _load_default(path, ind_dict=None, loader=None, channels="CZYX", **kwargs):
    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    data, meta, affine = bioio_loader(ind_dict, loader=loader, channels=channels, **kwargs)(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/010_io.ipynb #039b0cf5
def _apply_axis_index(data: np.ndarray, axes: str, ind_dict: dict | None = None):
    if not ind_dict:
        return data, axes

    index = [slice(None)] * data.ndim
    for axis, ind in ind_dict.items():
        if axis in axes:
            index[axes.index(axis)] = ind

    data = data[tuple(index)]
    axes = ''.join(axis for axis, ind in zip(axes, index) if not isinstance(ind, int))
    return data, axes


def _ensure_layout(data: np.ndarray, source_axes: str, channels: str) -> np.ndarray:
    current_axes = list(source_axes)

    for target_pos, axis in enumerate(channels):
        if axis in current_axes:
            source_pos = current_axes.index(axis)
            data = np.moveaxis(data, source_pos, target_pos)
            current_axes.insert(target_pos, current_axes.pop(source_pos))
        else:
            data = np.expand_dims(data, axis=target_pos)
            current_axes.insert(target_pos, axis)

    extra_axes = [i for i, axis in enumerate(current_axes) if axis not in channels]
    if extra_axes:
        data = np.squeeze(data, axis=tuple(extra_axes))

    return data



# %% ../nbs/010_io.ipynb #db2aa4df
@LOADER_REGISTRY.register(".jpg", ".jpeg", ".png", ".bmp")
def _load_pil(path, ind_dict=None, channels="CZYX", **kwargs):
    """
    Load PIL-supported 2D image formats.
    """
    path_str = str(path)
    if ind_dict is None:
        path_str, ind_dict = split_path(path_str)

    image = PILImage.create(path_str)
    if "C" not in channels and getattr(image, "mode", None) not in ("1", "L", "I", "F"):
        image = image.convert("L")
    data = np.array(image)

    if data.ndim == 2:
        source_axes = "YX"
    elif data.ndim == 3:
        source_axes = "YXC"
    else:
        raise ValueError(f"Unsupported PIL image shape: {data.shape}")

    data, source_axes = _apply_axis_index(data, source_axes, ind_dict)
    data = _ensure_layout(data, source_axes, channels)

    axis_sizes = dict(zip(channels, data.shape))
    meta = {
        "filepath": path_str,
        "source_shape": tuple(int(v) for v in data.shape),
        "dtype": str(data.dtype),
        "dimensions_present": source_axes,
        "image_size_x": axis_sizes.get("X"),
        "image_size_y": axis_sizes.get("Y"),
        "image_size_c": axis_sizes.get("C"),
        "layout": channels,
        "mode": image.mode,
    }
    meta = {k: v for k, v in meta.items() if v is not None}

    return MetaTensor(x=data, affine=np.eye(4), meta=meta)


# %% ../nbs/010_io.ipynb #0bbc84e8
@LOADER_REGISTRY.register(".npy")
def _load_npy(path, **kwargs):
    data = np.load(path)
    return MetaTensor(x=data) 


# %% ../nbs/010_io.ipynb #27932955
@LOADER_REGISTRY.register(".npz")
def _load_npz(path, **kwargs):
    npz_file = np.load(path)

    key = kwargs.get('npz_key') or next(iter(npz_file.keys()))
    if key not in npz_file:
        raise KeyError(f"Key '{key}' not found. Available: {list(npz_file.keys())}")

    return MetaTensor(x=npz_file[key])



# %% ../nbs/010_io.ipynb #6d8439bf
@LOADER_REGISTRY.register(".h5", ".hdf5")
def _load_hdf5(path, channels="CZYX", **kwargs):
    path_str = str(path)

    hdf5_ext = [ext for ext in ('.h5', '.hdf5') if ext in path_str]
    path, dataset, patch = split_hdf_path(path_str, hdf5_exts=hdf5_ext)

    data, meta, affine = hdf5_loader(dataset=dataset, patch=patch, hdf5_exts=hdf5_ext, channels=channels)(path)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/010_io.ipynb #e4ff27ed
@LOADER_REGISTRY.register(".tiff", ".tif")
def _load_tiff(path, ind_dict=None, channels="CZYX", **kwargs):
    """
    Load a TIFF image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """

    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    
    # ome.tiff require a separate loader than regular tiff
    if is_ome_tiff(Path(path_str)):
       image_loader = OmeTiffReader
    else:
        image_loader = TiffReader

    data, meta, affine = bioio_loader(ind_dict, loader=image_loader, channels=channels, **kwargs)(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)


# %% ../nbs/010_io.ipynb #6f152957
@LOADER_REGISTRY.register(".czi")
def _load_czi(path, ind_dict=None, channels="CZYX", **kwargs):
    """
    Load a CZI image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """
    
    kwargs.setdefault('use_aicspylibczi', True)
    kwargs.setdefault('include_subblock_metadata', False)

    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    
    # bioio-czi needs to operate in aicspylibczi mode to access tiles

    data, meta, affine = bioio_loader(ind_dict=ind_dict,
                                      loader=CziReader, 
                                      channels=channels,
                                      **kwargs,
                                      )(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/010_io.ipynb #42c796c8
def _get_loader(path: Path):
    """
    Select appropriate loader based on file format.

    Priority:
        1. registry-based loader (exact match)
        2. format-based fallback (via extract_formats)
        3. default loader
    """

    # 1. Registry-based detection (fast path)
    loader = LOADER_REGISTRY.get(path)
    if loader:
        return loader

    # 2. Format-based detection (HDF5-aware)
    fmt = extract_formats(path)[0]

    if fmt == "HDF5":
        return _load_hdf5

    # 3. Default fallback
    return _load_default

# %% ../nbs/010_io.ipynb #d9629282
def _to_dtype_if_needed(metatensor: MetaTensor, dtype: torch.dtype | None = torch.float32) -> MetaTensor:
    if dtype is None or metatensor.dtype == dtype:
        return metatensor
    return metatensor.to(dtype)


def _attach_load_metadata(
    metatensor: MetaTensor,
    path: Path,
    channels: str,
    fmt: str | None = None,
) -> MetaTensor:
    meta = metatensor.meta
    meta["filepath"] = str(path)
    meta["format"] = extract_formats(path)[0] if fmt is None else fmt
    meta["layout"] = channels
    return metatensor


def _load_and_preprocess(
    file_path: PathLike,
    transforms: Callable|Iterable[Callable]|None =None,
    channels: str ="CZYX",
    ind_dict: dict|None =None,
    dtype: torch.dtype = torch.float32,
    **kwargs,
) -> MetaTensor:
    """
    Load image and apply preprocessing transforms.

    Also attaches file path, format, and layout metadata.
    """
    path = Path(file_path)
    image_loader = _get_loader(path)

    metatensor = image_loader(
        path,
        channels=channels,
        ind_dict=ind_dict,
        **kwargs,
    )
    metatensor = _to_dtype_if_needed(metatensor, dtype)
    metatensor = _preprocess(metatensor, transforms)

    return _attach_load_metadata(metatensor, path, channels)


# %% ../nbs/010_io.ipynb #80e604f7
def _load_and_preprocess_dict(
    obj: dict,
    keys: str | Iterable[str],
    transforms: Callable | Iterable[Callable] | None = None,
    channels: str = "CZYX",
    ind_dict: dict | None = None,
    dtype: torch.dtype = torch.float32,
    **kwargs,
) -> dict:
    """
    Load images from paths stored inside dictionary keys and apply preprocessing.

    Args:
        obj:
            Input dictionary.
        keys:
            Key or iterable of keys containing file paths.
        transforms:
            Callable or iterable of callables.
        channels:
            Channel layout string.
        ind_dict:
            Optional index dictionary.
        **kwargs:
            Optional keyword arguments for the image loader.

    Returns:
        dict:
            Updated dictionary with loaded/preprocessed MetaTensor(s).
    """
    if isinstance(keys, str):
        keys = [keys]

    paths = {}
    original_shapes = {}

    for key in keys:
        path = Path(obj[key])
        paths[key] = path

        image_loader = _get_loader(path)
        tensor = image_loader(
            path,
            channels=channels,
            ind_dict=ind_dict,
            **kwargs,
        )
        tensor = _to_dtype_if_needed(tensor, dtype)

        original_shapes[key] = tensor.shape
        obj[key] = tensor

    obj = _preprocess_dict(obj, transforms)

    for key in keys:
        tensor = obj[key]
        if not isinstance(tensor, MetaTensor):
            continue

        meta = tensor.meta
        meta["size_loaded"] = original_shapes[key]
        meta["size_after_tfms"] = getattr(tensor, "shape", None)
        _attach_load_metadata(tensor, paths[key], channels)

    return obj


# %% ../nbs/010_io.ipynb #08b998f4
def _multi_sequence_stream(
    image_paths: Sequence[PathLike],
    transforms=None,
    channels="CZYX",
    ind_dict=None,
    dtype: torch.dtype = torch.float32,
    **kwargs,
) -> Iterable[MetaTensor]:
    """
    Lazily yield preprocessed image samples.

    Args:
        image_paths: Iterable of file paths.
        transforms: Optional transforms.
        reader: Optional reader.
        npz_key: Optional NPZ key.

    Yields:
        tuple (image, metadata)
    """
    for p in image_paths:
        yield _load_and_preprocess(
            p,
            transforms=transforms,
            channels=channels,
            ind_dict=ind_dict,
            dtype=dtype,
            **kwargs,
        )

# %% ../nbs/010_io.ipynb #050e2bb0
def _multi_sequence_stream_dict(
    objs: Sequence[dict],
    keys: str | Iterable[str],
    transforms=None,
    channels: str = "CZYX",
    ind_dict=None,
    dtype: torch.dtype = torch.float32,
    **kwargs,
) -> Iterable[dict]:
    """
    Lazily yield dictionary samples with loaded and preprocessed MetaTensor objects.

    Each yielded item preserves the original dictionary structure, where
    specified keys contain MetaTensor objects instead of file paths.

    Args:
        objs:
            Sequence of input dictionaries containing file paths.
        keys:
            Key or iterable of keys containing file paths.
        transforms:
            Optional transforms applied to loaded tensors.
        loader:
            Optional reader/loader function.
        channels:
            Channel layout string.
        ind_dict:
            Optional index dictionary.
        npz_key:
            Optional NPZ key.

    Yields:
        dict:
            Dictionary with loaded and preprocessed MetaTensor(s).
    """
    if isinstance(keys, str):
        keys = [keys]

    for obj in objs:
        yield _load_and_preprocess_dict(
            obj=obj.copy(),
            keys=keys,
            transforms=transforms,
            channels=channels,
            ind_dict=ind_dict,
            dtype=dtype,
            **kwargs,
        )

# %% ../nbs/010_io.ipynb #c4fc78a7
def _stack(
    input_metatensors: Sequence[MetaTensor],
    stack_axis: str = "C",
    channels: str = "CZYX",
    squeeze: bool = True,
) -> MetaTensor:
    """
    Stack a sequence of MetaTensors into a single tensor.
    
    Args:
        input_metatensors: Sequence of MetaTensors to stack.
        stack_axis: Axis along which to stack (e.g., "S" for sequence).
        channels: Desired channel order for output (e.g., "CZYX").
        squeeze: Whether to squeeze singleton dimensions before stacking.
    
    Returns:
        Stacked tensor with metadata from each input tensor indexed by position.
    
    Raises:
        ValueError: If input is empty or invalid parameters provided.
    """
    # Validation
    if not input_metatensors:
        raise ValueError("input_metatensors cannot be empty")
    if not stack_axis or len(stack_axis) != 1:
        raise ValueError(f"stack_axis must be a single character, got {stack_axis!r}")
    if not channels or not all(c in "SCZYX" for c in channels):
        raise ValueError(f"channels must contain valid axis labels, got {channels!r}")
    
    # Squeeze tensors
    processed = [
        t.squeeze() if squeeze else t
        for t in input_metatensors
    ]
    
    # Preserve metadata from each original tensor
    metadata_dict = {i: m.meta for i, m in enumerate(input_metatensors)}
    
    # Case A: stack_axis is new (not in current channels)
    if stack_axis not in channels:
        # Stack along new dimension at position 0
        stacked = torch.stack(processed, dim=0)
        # Update metadata: new axis prepended to layout, plus indexed original metadata
        stacked.meta.update({
            'layout': stack_axis + channels,
            'tensors': metadata_dict
        })
        return stacked
    
    # Case B: stack_axis exists in channels → concatenate along that axis
    axis_idx = channels.index(stack_axis)
    
    # Stack first to add a new dimension, then move it to the target position
    stacked = torch.stack(processed, dim=0)
    
    # Move the stacking dimension to the target axis position
    # (adjust for the fact that we stacked at dim=0)
    target_dim = axis_idx + 1  # +1 because stack added a dimension at position 0
    stacked = torch.moveaxis(stacked, 0, target_dim)
    
    # Flatten the stacking dimension into the target axis
    shape = list(stacked.shape)
    shape[axis_idx:axis_idx+2] = [shape[axis_idx] * shape[axis_idx+1]]
    output = stacked.reshape(shape)
    
    # Update metadata with indexed original metadata
    output.meta.update({
        'layout': channels,
        'tensors': metadata_dict
    })
    
    return output


def _meta_from_layout(
    shape: tuple[int, ...],           # The shape of the image tensor
    layout: str,                      # The channel layout string (e.g., "CZYX")
    meta: dict | None = None,         # Existing metadata used to avoid repeated BioIO fields
) -> dict[str, int | str | tuple | None]:
    """
    Extract output-specific metadata from a channel layout.

    Existing BioIO metadata is used to avoid adding aliases such as ``width``
    when ``image_size_x`` is already present.
    """
    if len(shape) != len(layout):
        raise ValueError(f"{shape} vs {layout}")

    shape = tuple(int(v) for v in shape)
    meta = {} if meta is None else meta

    def axis_size(axis):
        idx = layout.find(axis)
        return None if idx == -1 else shape[idx]

    out = {
        "size_output": shape,
        MetaKeys.SPATIAL_SHAPE: tuple(
            axis_size(axis) for axis in "ZYX" if axis in layout
        ),
    }

    # Avoid duplicating flattened BioIO StandardMetadata fields.
    for key, axis, bioio_key in (
        ("width", "X", "image_size_x"),
        ("height", "Y", "image_size_y"),
        ("depth", "Z", "image_size_z"),
        ("channels", "C", "image_size_c"),
        ("frames", "T", "image_size_t"),
        ("sequence", "S", None),
    ):
        value = axis_size(axis)
        if value is not None and key not in meta and (bioio_key is None or bioio_key not in meta):
            out[key] = value

    c = axis_size("C")
    if "mode" not in meta:
        out["mode"] = "L" if c is None else {1: "L", 3: "RGB"}.get(c, f"multichannel ({c})")

    if "kind" not in meta:
        sequence = axis_size("S")
        frames = axis_size("T")
        depth = axis_size("Z")
        if sequence is not None and sequence > 1:
            out["kind"] = "sequence"
        elif frames is not None and frames > 1:
            out["kind"] = "video"
        elif depth is not None and depth > 1:
            out["kind"] = "volume"
        else:
            out["kind"] = "image"

    if MetaKeys.ORIGINAL_CHANNEL_DIM not in meta:
        channel_dim = layout.find("C")
        out[MetaKeys.ORIGINAL_CHANNEL_DIM] = channel_dim if channel_dim != -1 else float("nan")

    return out


def _to_numpy(x):
    return x.detach().cpu().numpy()


def _extract_meta(
    metatensor: MetaTensor,
    metatensors: Sequence[MetaTensor] | None = None,
):
    if metatensors is None:
        return metatensor.meta

    return {
        i: mt.meta
        for i, mt in enumerate(metatensors)
    }


_OUTPUT_MODES = {
    "metatensor",
    "tensor",
    "tensor+meta",
    "nparray",
    "nparray+meta",
}


def _format_output(
    output: str,
    metatensor: MetaTensor,
    metatensors: Sequence[MetaTensor] | None = None,
):
    """
    Convert MetaTensor outputs into the requested representation.
    """
    if output == "metatensor":
        return metatensor

    if output.startswith("tensor"):
        data = metatensor.as_tensor()

    elif output.startswith("nparray"):
        data = _to_numpy(metatensor)

    else:
        raise ValueError(
            f"Unknown output mode: {output}. "
            f"Expected one of {_OUTPUT_MODES}"
        )

    if output.endswith("+meta"):
        return data, _extract_meta(metatensor, metatensors)

    return data



# %% ../nbs/010_io.ipynb #f4177cc4
def image_reader(
    file_path: PathLike | Sequence[PathLike],
    lazy: bool = False,
    output: str = "metatensor",
    transforms: Callable | list[Callable] | None = None,
    channels: str = "CZYX",
    ind_dict: dict | None = None,
    dtype=torch.float32,
    squeeze: bool = False,
    stack_axis: str = "C",
    **kwargs,
) -> (
    MetaTensor
    | np.ndarray
    | tuple[np.ndarray, dict]
    | torch.Tensor
    | tuple[torch.Tensor, dict]
):
    """
    Main entry point for image loading.

    Supports:
        - single-image loading
        - multi-image loading
        - lazy streaming
        - tensor / numpy / MetaTensor outputs
        - configurable stacking layouts

    Parameters
    ----------
    file_path:
        Single image path or sequence of image paths.

    lazy:
        If True and multiple paths are provided, images are streamed
        lazily instead of eagerly loaded.

    output:
        Output representation.

        Supported values:
            - "metatensor"
            - "tensor"
            - "tensor+meta"
            - "nparray"
            - "nparray+meta"

    transforms:
        Optional preprocessing transforms.

    channels:
        Axis layout string describing image dimensions.

    ind_dict:
        Optional indexing dictionary for partial loading.

    dtype:
        Output tensor dtype.

    squeeze:
        Remove singleton dimensions before returning.

    stack_axis:
        Axis used for stacking multi-image inputs.

        If present in `channels`, stacking occurs along that axis.

        Otherwise, a new axis is inserted.

    **kwargs:
        Additional loader-specific arguments.
    """

    if output not in _OUTPUT_MODES:
        raise ValueError(
            f"Unknown output mode: {output}. "
            f"Expected one of {_OUTPUT_MODES}"
        )

    is_multi = (
        isinstance(file_path, Sequence)
        and not isinstance(file_path, (str, Path))
    )

    def _load(path):
        return _load_and_preprocess(
            path,
            transforms=transforms,
            channels=channels,
            ind_dict=ind_dict,
            dtype=dtype,
            **kwargs,
        )

    # =====================================================
    # MULTI-IMAGE CASE
    # =====================================================

    if is_multi:

        if lazy:
            metatensors = _multi_sequence_stream(
                file_path,
                transforms=transforms,
                channels=channels,
                ind_dict=ind_dict,
                dtype=dtype,
                **kwargs,
            )
        else:
            metatensors = [_load(p) for p in file_path]

        metatensor = _stack(
            metatensors,
            stack_axis=stack_axis,
            channels=channels,
            squeeze=squeeze,
        )

        metatensor.meta.update(
            _meta_from_layout(
                metatensor.shape,
                metatensor.meta["layout"],
                meta=metatensor.meta,
            )
        )

        return _format_output(
            output=output,
            metatensor=metatensor,
            metatensors=metatensors,
        )

    # =====================================================
    # SINGLE-IMAGE CASE
    # =====================================================

    metatensor = _load(file_path)

    if squeeze:
        metatensor = metatensor.squeeze()

    metatensor.meta.update(
        _meta_from_layout(
            metatensor.shape,
            channels,
            meta=metatensor.meta,
        )
    )

    return _format_output(
        output=output,
        metatensor=metatensor,
    )


# %% ../nbs/010_io.ipynb #3135d535
def image_reader_dict(
    data: dict,
    keys: str | Iterable[str],
    lazy: bool = False,
    output: str = "metatensor",
    transforms: Callable | list[Callable] | None = None,
    channels: str = "CZYX",
    ind_dict: dict | None = None,
    dtype: torch.dtype = torch.float32,
    squeeze: bool = False,
    stack_axis: str = "C",
    **kwargs,
):
    """
    Load images from dictionary keys.

    Supports:
        - single or multi-image entries
        - eager or lazy loading
        - tensor / numpy / MetaTensor outputs
        - metadata preservation

    Parameters
    ----------
    data:
        Input dictionary containing image paths.

    keys:
        Dictionary keys containing image paths or sequences of paths.

    lazy:
        If True, multi-image sequences are streamed lazily.

    output:
        Output representation.

        Supported values:
            - "metatensor"
            - "tensor"
            - "tensor+meta"
            - "nparray"
            - "nparray+meta"

    transforms:
        Optional preprocessing transforms.

    channels:
        Axis layout string.

    ind_dict:
        Optional indexing dictionary.

    dtype:
        Output tensor dtype.

    squeeze:
        Remove singleton dimensions.

    stack_axis:
        Axis used when stacking multi-image inputs.

    **kwargs:
        Additional loader-specific arguments.

    Returns
    -------
    dict
        Dictionary with loaded image objects replacing file paths.
    """

    if output not in _OUTPUT_MODES:
        raise ValueError(
            f"Unknown output mode: {output}. "
            f"Expected one of {_OUTPUT_MODES}"
        )

    if not keys:
        return data.copy()

    if isinstance(keys, str):
        keys = [keys]

    out = data.copy()

    def _load(obj):
        return _load_and_preprocess_dict(
            obj=obj,
            keys=keys,
            transforms=transforms,
            channels=channels,
            ind_dict=ind_dict,
            dtype=dtype,
            **kwargs,
        )

    def _iter_multi(dict_list):

        if lazy:
            return _multi_sequence_stream_dict(
                objs=dict_list,
                keys=keys,
                transforms=transforms,
                channels=channels,
                ind_dict=ind_dict,
                dtype=dtype,
                **kwargs,
            )

        return [_load(d) for d in dict_list]

    for k in keys:

        if k not in out:
            continue

        obj = out[k]

        is_multi = (
            isinstance(obj, Sequence)
            and not isinstance(obj, (str, Path))
        )

        # =====================================================
        # MULTI-IMAGE CASE
        # =====================================================

        if is_multi:

            dict_list = [{k: p} for p in obj]

            loaded = _iter_multi(dict_list)

            metatensors = [d[k] for d in loaded]

            metatensor = _stack(
                metatensors,
                stack_axis=stack_axis,
                channels=channels,
                squeeze=squeeze,
            )

            metatensor.meta.update(
                _meta_from_layout(
                    metatensor.shape,
                    metatensor.meta["layout"],
                )
            )

            out[k] = _format_output(
                output=output,
                metatensor=metatensor,
                metatensors=metatensors,
            )

        # =====================================================
        # SINGLE-IMAGE CASE
        # =====================================================

        else:

            loaded = _load({k: obj})

            metatensor = loaded[k]

            if squeeze:
                metatensor = metatensor.squeeze()

            metatensor.meta.update(
                _meta_from_layout(
                    metatensor.shape,
                    channels,
                    meta=metatensor.meta,
                )
            )

            out[k] = _format_output(
                output=output,
                metatensor=metatensor,
            )

    return out


# %% ../nbs/010_io.ipynb #5a78f57f
class BioImageReader(ImageReader):
    def __init__(
        self,
        converter: Callable[[MetaTensor], MetaTensor] | None = None,  # A callable that takes a MetaTensor and returns a MetaTensor
        reverse_indexing: bool = False,
        **kwargs,
    ):
        super().__init__()
        self.converter = converter
        self.reverse_indexing = reverse_indexing
        self.kwargs = kwargs

    # --------------------------------------------------
    def verify_suffix(self, filename:Sequence[PathLike] | PathLike) -> bool:
        suffixes = self._get_supported_suffixes()
        return is_supported_format(filename, suffixes)


    def _get_supported_suffixes(self) -> list[str]:
        """
        Collect supported suffixes from loader registry removing leading dots.
        """
        # Extract keys from the inner registry dictionary and flatten any nested structures
        return [ext.lstrip('.') for ext in LOADER_REGISTRY._loaders.keys()]

    # --------------------------------------------------
    def read(self, data: PathLike | Sequence[PathLike] | np.ndarray, **kwargs) -> MetaTensor:
        kwargs_ = {**self.kwargs, **kwargs}
        
        if isinstance(data, Sequence) and not isinstance(data, (str, Path)) and len(data) == 1:
            data = data[0]

        mt = image_reader(
            data,
            **kwargs_,
        )

        if self.converter:
            mt = self.converter(mt)

        return mt

    # --------------------------------------------------
    def get_data(self, img: MetaTensor) -> tuple[np.ndarray, dict]:

        if self.reverse_indexing and img.ndim >= 2:
            img = MetaTensor(
                x=img.swapaxes(-1, -2),
                meta=img.meta,
            )

        # extract numpy array
        array = img.as_tensor().cpu().numpy()

        # ensure plain dict
        meta = dict(img.meta)

        return array, meta 
    
    def _get_spatial_shape(self, img: MetaTensor):
        m = img.meta
        spatial_shape = m.get(MetaKeys.SPATIAL_SHAPE)
        if spatial_shape is not None:
            return tuple(reversed(spatial_shape))
        return tuple(
            v for v in (
                m.get("width", m.get("image_size_x")),
                m.get("height", m.get("image_size_y")),
                m.get("depth", m.get("image_size_z")),
            )
            if v is not None
        )


# %% ../nbs/010_io.ipynb #49b7b1f2
# Re-exporting MONAI's standard loaders for convenience within bonsai
LoadImage = LoadImage
LoadImaged = LoadImaged
