"""Metric tracking and analysis tools"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/060_metrics.ipynb.

# %% auto #0
__all__ = ['METRIC_BACKENDS', 'register_metric_backend', 'FastaiMetric', 'MetricBackend', 'MonaiMetricBackend',
           'FastaiMetricBackend', 'BioMetric', 'MSEMetric', 'SSIMMetric', 'PSNRMetric', 'MSSSIMMetric', 'MAEMetric',
           'RMSEMetric', 'DiceMetric', 'IoUMetric', 'GeneralizedDiceScore', 'PanopticQualityMetric', 'AccuracyMetric',
           'F1ScoreMetric', 'JaccardMetric', 'PrecisionMetric', 'RecallMetric', 'MatthewsCorrCoefMetric',
           'ROCAUCMetric', 'AveragePrecisionMetric', 'ConfusionMatrixMetric', 'HausdorffDistanceMetric',
           'SurfaceDistanceMetric', 'SurfaceDiceMetric', 'FIDMetric', 'MMDMetric', 'MetricsReloadedBinaryFastai',
           'MetricsReloadedBinary', 'MetricsReloadedCategorical', 'FRCMetric', 'VarianceMetric', 'LabelQualityScore']

# %% ../nbs/060_metrics.ipynb #09106178
from functools import partial
# =================================
# PyTorch
# =================================
from torch import (
    abs,
    argmax,
    div,
    isnan,
    is_tensor,
    isinf,
    real,
    sigmoid,
    where,
    zeros_like,
    cat,
    full_like,
    nanmean,
    nansum,
    sum,
    zeros,
    float32,
    all,
    eq,
)
from torch.nn.functional import one_hot, softmax

# =================================
# fastai
# =================================
import fastai.metrics as fm
from fastai.vision.all import Metric

# =================================
# MONAI
# =================================
import monai.metrics as mm

# =================================
# bonsai
# =================================
from .losses import FRCLoss
from .backend import get_backend
from .utils import *

# %% ../nbs/060_metrics.ipynb #05d4562d
METRIC_BACKENDS = {}

def register_metric_backend(name):
    """Register a metric backend."""
    def decorator(backend):
        if name in METRIC_BACKENDS:
            raise ValueError(f"Metric backend already registered: {name}")
        METRIC_BACKENDS[name] = backend
        return backend

    return decorator

# %% ../nbs/060_metrics.ipynb #711c1484
class FastaiMetric(Metric):
    """Adapt a stateful bonsai metric to the fastai Metric interface."""

    def __init__(self, metric, name=None):
        self.metric = metric
        self._name = name or metric.__class__.__name__.removesuffix("Metric")

    @property
    def name(self):
        return self._name

    def reset(self):
        self.metric.reset()

    def accumulate(self, learn):
        target = learn.yb[0] if isinstance(learn.yb, (tuple, list)) else learn.yb
        pred, target = self._prepare(learn.pred, target)
        self.metric(pred, target)

    def _prepare(self, pred, target):
        return pred, target

    @property
    def value(self):
        value = self.metric.aggregate()

        if isinstance(value, tuple):
            value = value[0]

        if hasattr(value, "numel") and value.numel() == 1:
            return value.item()

        return value

# %% ../nbs/060_metrics.ipynb #7cd10510
class MetricBackend:
    """
    Base class for metric backend adapters.

    A backend converts a metric class and its constructor arguments into the
    metric implementation required by a training framework.
    """

    def create(self, metric_cls, *args, **kwargs):
        """
        Instantiate a metric for the backend.

        Parameters
        ----------
        metric_cls : type
            Metric class to instantiate.
        *args
            Positional arguments passed to the metric constructor.
        **kwargs
            Keyword arguments passed to the metric constructor.

        Returns
        -------
        object
            Instantiated metric.
        """
        return metric_cls(*args, **kwargs)


# %% ../nbs/060_metrics.ipynb #3261f51c
@register_metric_backend("monai")
class MonaiMetricBackend(MetricBackend):
    """
    Backend for native MONAI metrics.

    MONAI metrics are instantiated directly without additional adaptation.
    """

    pass


# %% ../nbs/060_metrics.ipynb #20beaab1
@register_metric_backend("fastai")
class FastaiMetricBackend(MetricBackend):
    """
    Backend for metrics used with the fastai training engine.

    Explicit fastai metric implementations are instantiated directly.
    Metrics that do not provide a fastai-specific implementation are adapted
    dynamically by combining their native implementation with
    ``FastaiMetricMixin``.
    """

    def create(self, metric_cls, *args, **kwargs):
        """
        Create a fastai-compatible metric.

        Parameters
        ----------
        metric_cls : type
            Metric implementation to instantiate.
        *args
            Positional arguments passed to the metric constructor.
        **kwargs
            Keyword arguments passed to the metric constructor.

        Returns
        -------
        object
            Fastai-compatible metric instance.
        """
        
        metric = metric_cls(*args, **kwargs)

        if isinstance(metric, Metric):
            # print(f"Creating fastai metric: {metric_cls.__name__}")
            return metric

        # print(f"Adapting metric {metric_cls.__name__} to fastai interface")

        return FastaiMetric(metric)

# %% ../nbs/060_metrics.ipynb #0661c10a
class BioMetric:
    """
    Backend-independent interface for metrics in bonsai.

    ``BioMetric`` provides a common interface for metrics implemented across
    different deep-learning backends. A metric can define a backend-specific
    implementation through attributes such as ``_torch``, ``_monai``,
    ``_fastai``, or ``_keras``. If no implementation is defined for the
    active backend, ``_default`` is used instead.

    The active backend is selected globally with
    :func:`bonsai.set_backend` and is obtained through
    :func:`bonsai.get_backend`. Consequently, metrics do not expose a
    ``backend`` argument.

    Attributes
    ----------
    _default : callable, optional
        Default metric implementation used when no backend-specific
        implementation is available.
    _<backend> : callable, optional
        Backend-specific metric implementation. For example, ``_monai``
        or ``_fastai``. When defined, it takes precedence over
        ``_default`` for the corresponding active backend.

    Examples
    --------
    Select the backend globally and instantiate metrics normally:

    >>> bonsai.set_backend("monai")
    >>> metric = DiceMetric()

    The same metric interface can then be used with another backend:

    >>> bonsai.set_backend("fastai")
    >>> metric = DiceMetric()
    """

    _default = None

    @classmethod
    def _get_metric(cls, backend):
        """
        Return the metric implementation for a registered backend.
        """
        if backend not in METRIC_BACKENDS:
            raise ValueError(
                f"Unknown metric backend '{backend}'. "
                f"Available metric backends: {list(METRIC_BACKENDS)}"
            )

        metric_cls = getattr(cls, f"_{backend}", None)
        if metric_cls is None:
            metric_cls = cls._default

        if metric_cls is None:
            raise ValueError(
                f"No metric implementation for backend '{backend}' "
                f"and no default implementation is defined for "
                f"{cls.__name__}."
            )

        return metric_cls

    @classmethod
    def _create_metric(cls, backend, *args, **kwargs):
        """
        Create the metric using the selected backend adapter.
        """
        metric_cls = cls._get_metric(backend)
        backend_cls = METRIC_BACKENDS[backend]

        return backend_cls().create(
            metric_cls,
            *args,
            **kwargs,
        )

    @property
    def name(self):
        """
        Return the metric name.
        """
        return self.__class__.__name__

    def __new__(cls, *args, **kwargs):
        """
        Instantiate the metric using the globally active backend.
        """
        backend = get_backend()

        return cls._create_metric(
            backend,
            *args,
            **kwargs,
        )

# %% ../nbs/060_metrics.ipynb #4960aa4d
class MSEMetric(BioMetric):
    _default = mm.MSEMetric


class SSIMMetric(BioMetric):
    _default = mm.SSIMMetric


class PSNRMetric(BioMetric):
    _default = mm.PSNRMetric


class MSSSIMMetric(BioMetric):
    _default = mm.MultiScaleSSIMMetric


class MAEMetric(BioMetric):
    _default = mm.MAEMetric


class RMSEMetric(BioMetric):
    _default = mm.RMSEMetric

# %% ../nbs/060_metrics.ipynb #925bfd79
class _FastaiDice(Metric):
    """
    Computes Dice score for prediction-ground-truth label pairs.

    This Fastai implementation mirrors the interface and semantics of
    :class:`monai.metrics.DiceMetric`.

    Predictions and targets may be provided as either:

    - one-hot/channel-first tensors ``BCHW[D]``, or
    - single-channel label maps ``B1HW[D]``.

    No activation is applied to predictions. When label maps are supplied,
    ``num_classes`` must be specified.

    Parameters
    ----------
    include_background : bool, default=True
        Whether to include the background class (channel 0).
    reduction : str, default="mean"
        Reduction applied to the per-sample, per-channel Dice values.
        Supported values are ``"none"``, ``"mean"``, ``"sum"``,
        ``"mean_batch"``, and ``"mean_channel"``.
    get_not_nans : bool, default=False
        Whether to return the number of valid, non-NaN values.
    ignore_empty : bool, default=True
        Whether to ignore samples whose ground-truth segmentation is empty.
        Ignored values are represented by NaN.
    num_classes : int or None, default=None
        Number of classes when predictions and/or targets are supplied as
        single-channel label maps.
    return_with_label : bool or list[str], default=False
        When ``reduction="mean_batch"``, optionally return a dictionary
        containing one value per channel.
    """

    def __init__(
        self,
        include_background: bool = True,
        reduction: str = "mean",
        get_not_nans: bool = False,
        ignore_empty: bool = True,
        num_classes: int | None = None,
        return_with_label: bool | list[str] = False,
    ):
        self.include_background = include_background
        self.reduction = reduction
        self.get_not_nans = get_not_nans
        self.ignore_empty = ignore_empty
        self.num_classes = num_classes
        self.return_with_label = return_with_label
        self.reset()

    def reset(self):
        self._values = []

    def accumulate(self, learn):
        pred = learn.pred
        targ = learn.yb[0] if isinstance(learn.yb, (tuple, list)) else learn.yb

        values = self._compute_tensor(pred, targ)
        self._values.append(values.detach().cpu())

    def _compute_tensor(self, pred, targ):
        if pred.ndim < 3:
            raise ValueError(
                f"pred should have at least 3 dimensions "
                f"(batch, channel, spatial), got {pred.ndim}."
            )

        pred, targ = self._prepare_inputs(pred, targ)

        # B x C x spatial
        pred = pred.reshape(pred.shape[0], pred.shape[1], -1)
        targ = targ.reshape(targ.shape[0], targ.shape[1], -1)

        intersection = (pred * targ).sum(dim=2)
        pred_sum = pred.sum(dim=2)
        targ_sum = targ.sum(dim=2)

        denominator = pred_sum + targ_sum

        dice = full_like(intersection, float("nan"))

        non_empty = targ_sum > 0
        dice[non_empty] = (
            2.0 * intersection[non_empty] / denominator[non_empty]
        )

        if not self.ignore_empty:
            empty_target = targ_sum == 0
            empty_both = empty_target & (pred_sum == 0)
            dice[empty_both] = 1.0

        if not self.include_background:
            dice = dice[:, 1:]

        return dice

    def _prepare_inputs(self, pred, targ):
        # Already channel-formatted.
        if pred.shape[1] > 1:
            if targ.ndim == pred.ndim and targ.shape[1] == pred.shape[1]:
                return pred, targ

            # Prediction is one-hot/channel formatted, target is a label map.
            if targ.ndim == pred.ndim and targ.shape[1] == 1:
                targ = self._label_to_onehot(targ, pred.shape[1])

            elif targ.ndim == pred.ndim - 1:
                targ = self._label_to_onehot(targ.unsqueeze(1), pred.shape[1])

            return pred, targ

        # Label-map input.
        if self.num_classes is None:
            raise ValueError(
                "num_classes must be specified when predictions are "
                "single-channel label maps."
            )

        pred = self._label_to_onehot(pred, self.num_classes)

        if targ.ndim == pred.ndim and targ.shape[1] == 1:
            targ = self._label_to_onehot(targ, self.num_classes)
        elif targ.ndim == pred.ndim - 1:
            targ = self._label_to_onehot(targ.unsqueeze(1), self.num_classes)

        return pred, targ

    @staticmethod
    def _label_to_onehot(label, num_classes):
        label = label.long()
        shape = (label.shape[0], num_classes, *label.shape[2:])

        onehot = zeros(
            shape,
            dtype=float32,
            device=label.device,
        )

        return onehot.scatter_(1, label, 1.0)

    def _aggregate(self):
        if not self._values:
            return None

        data = cat(self._values, dim=0)

        if self.reduction == "none":
            value = data

        elif self.reduction == "mean":
            value = nanmean(data)

        elif self.reduction == "sum":
            value = nansum(data)

        elif self.reduction == "mean_batch":
            value = nanmean(data, dim=0)

        elif self.reduction == "mean_channel":
            value = nanmean(data, dim=1)

        else:
            raise ValueError(
                f"Unsupported reduction: {self.reduction!r}. "
                "Expected one of: 'none', 'mean', 'sum', "
                "'mean_batch', 'mean_channel'."
            )

        if self.return_with_label and self.reduction == "mean_batch":
            if isinstance(self.return_with_label, bool):
                start = 0 if self.include_background else 1
                value = {
                    f"label_{i}": round(v.item(), 4)
                    for i, v in enumerate(value, start=start)
                }
            else:
                value = {
                    label: round(v.item(), 4)
                    for label, v in zip(self.return_with_label, value)
                }

        if self.get_not_nans:
            not_nans = sum(~isnan(data), dim=0)

            if self.reduction == "mean":
                not_nans = not_nans.sum()

            return value, not_nans

        return value

    @property
    def value(self):
        return self._aggregate()

# %% ../nbs/060_metrics.ipynb #a63e7732
class DiceMetric(BioMetric):
    """
    Compute the Dice coefficient for segmentation tasks.

    The Dice coefficient measures the spatial overlap between predicted and
    target segmentations. The metric supports single-channel label maps for
    multi-class segmentation as well as multi-channel representations for
    class-wise or multi-label segmentation.

    Parameters
    ----------
    include_background : bool, default=True
        Whether to include the background channel in the computation.

    reduction : str, default="mean"
        Reduction method used to combine per-sample and per-channel Dice
        scores. Common options include ``"mean"``, ``"sum"``,
        ``"mean_batch"``, ``"sum_batch"``, and ``"none"``.

    get_not_nans : bool, default=False
        If ``True``, also return the number of non-NaN values used in the
        reduction.

    ignore_empty : bool, default=True
        Whether to ignore cases where the target segmentation is empty.
        If ``True``, empty target regions do not contribute to the metric.

    num_classes : int, optional
        Number of classes when the input is provided as a single-channel
        label map. This may be required when the number of classes cannot be
        inferred from the input.

    return_with_label : bool or list of str, default=False
        If ``True``, return Dice values together with their class labels.
        A list of labels can be provided to explicitly name the classes.

    per_component : bool, default=False
        If ``True``, compute the Dice score independently for each binary
        component.

    Examples
    --------
    Compute the mean Dice score while excluding the background::

        dice = DiceMetric(
            include_background=False,
            reduction="mean",
        )

    Compute per-class Dice scores::

        dice = DiceMetric(
            include_background=False,
            reduction="none",
        )

    Notes
    -----
    The default backend uses MONAI's ``DiceMetric`` implementation. The
    fastai backend uses ``DiceFastaiMetric``, which combines MONAI's metric
    implementation with ``FastaiMetricMixin`` to provide the interface
    required by the fastai training loop.
    """

    _default = mm.DiceMetric
    _fastai = _FastaiDice

# %% ../nbs/060_metrics.ipynb #37db4336
class IoUMetric(BioMetric):
    _default = mm.MeanIoU

# %% ../nbs/060_metrics.ipynb #fb8decf3
class GeneralizedDiceScore(BioMetric):
    _default = mm.GeneralizedDiceScore

# %% ../nbs/060_metrics.ipynb #7df2d770
class PanopticQualityMetric(BioMetric):
    """
    Wrapper around monai.metrics.PanopticQualityMetric.

    Expects:
        pred  : (B, C, H, W) logits
        target: (B, H, W) or (B, 1, H, W) panoptic map
                Each pixel contains encoded panoptic label
                (semantic + instance id).

    All kwargs are forwarded to MONAI PanopticQualityMetric.
    """
    _default = mm.PanopticQualityMetric


# %% ../nbs/060_metrics.ipynb #ebbd8afc
def _accuracy_update(
    y_pred,
    y,
    axis=1,
    is_multilabel=False,
):
    """
    Compute the number of correct predictions and examples for accuracy.

    Supports binary, multiclass, and multilabel predictions.

    Parameters
    ----------
    y_pred : torch.Tensor
        Predictions. For multiclass, the class dimension is given by ``axis``.
    y : torch.Tensor
        Target labels.
    axis : int, default=1
        Class/channel dimension.
    is_multilabel : bool, default=False
        Whether the problem is multilabel classification.

    Returns
    -------
    tuple
        ``(num_correct, num_examples)``.
    """
    if is_multilabel:
        y_pred = y_pred.moveaxis(axis, -1)
        y = y.moveaxis(axis, -1)

        y_pred = y_pred.reshape(-1, y_pred.shape[-1])
        y = y.reshape(-1, y.shape[-1])

        correct = all(eq(y_pred, y), dim=-1)

    elif y_pred.ndim == y.ndim + 1:
        # Multiclass: select the predicted class.
        pred = argmax(y_pred, dim=axis)
        correct = eq(pred, y)

    else:
        # Binary classification.
        correct = eq(y_pred, y)

    correct = correct.reshape(-1)

    return correct.sum().item(), correct.numel()

# %% ../nbs/060_metrics.ipynb #2155ed8b
class _MonaiAccuracy:
    """
    MONAI-compatible implementation of accuracy.

    The implementation follows the semantics of Ignite's ``Accuracy``
    metric while exposing bonsai's backend-independent interface.
    """

    def __init__(
        self,
        axis=1,
        is_multilabel=False,
    ):
        self.axis = axis
        self.is_multilabel = is_multilabel
        self.reset()

    def reset(self):
        self.num_correct = 0
        self.num_examples = 0

    def update(self, y_pred, y):
        num_correct, num_examples = _accuracy_update(
            y_pred,
            y,
            axis=self.axis,
            is_multilabel=self.is_multilabel,
        )

        self.num_correct += num_correct
        self.num_examples += num_examples

    def compute(self):
        if self.num_examples == 0:
            return None

        return self.num_correct / self.num_examples

    @property
    def value(self):
        return self.compute()

# %% ../nbs/060_metrics.ipynb #b3182266
class _FastaiAccuracy(Metric):
    """
    Fastai implementation of the bonsai accuracy metric.

    Predictions and targets are obtained from ``learn.pred`` and
    ``learn.yb[0]`` respectively.
    """

    def __init__(
        self,
        axis=1,
        is_multilabel=False,
    ):
        self.axis = axis
        self.is_multilabel = is_multilabel
        self.reset()

    def reset(self):
        self.num_correct = 0
        self.num_examples = 0

    def accumulate(self, learn):
        num_correct, num_examples = _accuracy_update(
            learn.pred,
            learn.yb[0],
            axis=self.axis,
            is_multilabel=self.is_multilabel,
        )

        self.num_correct += num_correct
        self.num_examples += num_examples

    @property
    def value(self):
        if self.num_examples == 0:
            return None

        return self.num_correct / self.num_examples

# %% ../nbs/060_metrics.ipynb #ee436af2
class AccuracyMetric(BioMetric):
    """
    Accuracy metric for binary, multiclass, and multilabel classification.

    For multiclass predictions, the class with the largest prediction value
    along ``axis`` is selected. For binary and multilabel predictions,
    predictions are compared directly with the target values.

    Accuracy is accumulated as the ratio between the total number of correct
    predictions and the total number of examples, so batches are weighted
    according to their number of examples rather than averaged equally.

    Parameters
    ----------
    axis : int, default=1
        Class/channel dimension of multiclass or multilabel predictions.
    is_multilabel : bool, default=False
        Whether the task is multilabel classification.

    Notes
    -----
    The metric does not apply sigmoid, softmax, or thresholding. Predictions
    for binary and multilabel tasks must therefore already be in the same
    representation as the targets.
    """

    _default = _MonaiAccuracy
    _fastai = _FastaiAccuracy

# %% ../nbs/060_metrics.ipynb #db81e89f
def _monai_confusion_metric(metric_name):
    return partial(
        mm.ConfusionMatrixMetric,
        metric_name=metric_name,
    )

# %% ../nbs/060_metrics.ipynb #d7615ea1
class F1ScoreMetric(BioMetric):
    _default = _monai_confusion_metric("f1 score")
    _fastai = fm.F1ScoreMulti


class JaccardMetric(BioMetric):
    _default = _monai_confusion_metric("threat score")
    _fastai = fm.JaccardMulti


class PrecisionMetric(BioMetric):
    _default = _monai_confusion_metric("precision")
    _fastai = fm.PrecisionMulti


class RecallMetric(BioMetric):
    _default = _monai_confusion_metric("sensitivity")
    _fastai = fm.RecallMulti


class MatthewsCorrCoefMetric(BioMetric):
    _default = _monai_confusion_metric(
        "matthews correlation coefficient"
    )
    _fastai = fm.MatthewsCorrCoefMulti

# %% ../nbs/060_metrics.ipynb #a86d7472
class ROCAUCMetric(BioMetric):
    """
    Compute the area under the receiver operating characteristic curve
    (ROC-AUC) using MONAI.

    ROC-AUC summarizes the ability of a model to distinguish between
    positive and negative classes across all possible classification
    thresholds. For multiclass problems, MONAI supports different
    reduction strategies for combining the per-class AUC values.

    Parameters
    ----------
    average : str, default="macro"
        Reduction method used to combine AUC values across classes.
        The available options depend on the underlying MONAI
        implementation.

    get_not_nans : bool, default=False
        If ``True``, also return the number of valid, non-NaN AUC
        values when aggregating the metric.

    kwargs
        Additional keyword arguments are passed directly to MONAI's
        :class:`monai.metrics.ROCAUCMetric`.

    Notes
    -----
    With ``backend="fastai"``, predictions are optionally activated and
    converted to one-hot representations by ``ROCAUCFastaiMetric`` before
    being passed to MONAI.

    With the default MONAI backend, ``num_classes`` and ``act`` are not
    interpreted by this wrapper; they are specific to the fastai adapter.

    Examples
    --------
    Compute macro-averaged ROC-AUC with the default MONAI backend::
        set_backend("monai")
        metric = ROCAUCMetric()

    Use the metric with the fastai backend::
        set_backend("fastai")
        metric = ROCAUCMetric()

    """
    _default = mm.ROCAUCMetric
    _fastai = fm.RocAuc

# %% ../nbs/060_metrics.ipynb #06247a60
class AveragePrecisionMetric(BioMetric):
    _default = mm.AveragePrecisionMetric
    _fastai = fm.APScoreMulti

# %% ../nbs/060_metrics.ipynb #65149c1d
class ConfusionMatrixMetric(BioMetric):
    _default = mm.ConfusionMatrixMetric

# %% ../nbs/060_metrics.ipynb #06bef472
class HausdorffDistanceMetric(BioMetric):
    _default = mm.HausdorffDistanceMetric

# %% ../nbs/060_metrics.ipynb #a13fc7d6
class SurfaceDistanceMetric(BioMetric):
    _default = mm.SurfaceDistanceMetric

# %% ../nbs/060_metrics.ipynb #0481a590
class SurfaceDiceMetric(BioMetric):
    _default = mm.SurfaceDiceMetric

# %% ../nbs/060_metrics.ipynb #33fa9b46
class FIDMetric(BioMetric):
    _default = mm.FIDMetric

# %% ../nbs/060_metrics.ipynb #54b110e4
class MMDMetric(BioMetric):
    _default = mm.MMDMetric

# %% ../nbs/060_metrics.ipynb #bfad25b6
class MetricsReloadedBinaryFastai(FastaiMetric):
    """
    Fastai-compatible adapter for MONAI's ``MetricsReloadedBinary``.

    Metric computation and aggregation are delegated to MONAI, while
    ``FastaiMetric`` provides the fastai metric lifecycle.

    Parameters
    ----------
    metric_name : str
        Name of the MetricsReloaded metric to compute.
    *args
        Positional arguments passed to ``MetricsReloadedBinary``.
    **kwargs
        Additional keyword arguments passed to
        ``MetricsReloadedBinary``.

    Notes
    -----
    Only the primary target from ``learn.yb`` is used. Target extraction is
    handled by ``FastaiMetric.accumulate``.
    """

    def __init__(
        self,
        metric_name,
        *args,
        name=None,
        **kwargs,
    ):
        super().__init__(
            metric=mm.MetricsReloadedBinary(
                metric_name,
                *args,
                **kwargs,
            ),
            name=name or "MetricsReloadedBinary",
        )

# %% ../nbs/060_metrics.ipynb #8481bc99
class MetricsReloadedBinary(BioMetric):
    """
    Compute binary segmentation metrics using the MetricsReloaded framework.

    This metric evaluates predictions for binary segmentation tasks using
    the MetricsReloaded binary evaluation framework.

    Parameters
    ----------
    spacing : tuple, optional
        Physical spacing of the image dimensions. Used when computing
        metrics that depend on physical distances.

    """

    _default = mm.MetricsReloadedBinary
    _fastai = MetricsReloadedBinaryFastai


# %% ../nbs/060_metrics.ipynb #218af239
class MetricsReloadedCategorical(BioMetric):
    """
    Compute categorical segmentation metrics using the MetricsReloaded framework.

    This metric evaluates predictions for categorical or multi-class
    segmentation tasks using the MetricsReloaded categorical evaluation
    framework.

    Parameters
    ----------
    spacing : tuple, optional
        Physical spacing of the image dimensions. Used when computing
        metrics that depend on physical distances.

    """

    _default = mm.MetricsReloadedCategorical

# %% ../nbs/060_metrics.ipynb #bcb17f76
class _FRCLossMetric(mm.LossMetric):
    """
    MONAI metric wrapper for the Fourier Ring Correlation loss.

    This metric evaluates ``FRCLoss`` for each batch and aggregates the
    resulting loss values using MONAI's ``LossMetric`` implementation.

    Parameters
    ----------
    reduction : str, default="mean"
        Reduction applied when aggregating loss values across iterations.
        Supported modes include ``"none"``, ``"mean"``, ``"sum"``,
        ``"mean_batch"``, ``"sum_batch"``, ``"mean_channel"``, and
        ``"sum_channel"``.

    get_not_nans : bool, default=False
        If ``True``, ``aggregate`` also returns the number of non-NaN values.

    Notes
    -----
    The ``FRCLoss`` instance is created automatically and passed to MONAI's
    ``LossMetric`` as ``loss_fn``.
    """

    def __init__(
        self,
        reduction="mean",
        get_not_nans=False,
    ):
        super().__init__(
            loss_fn=FRCLoss(),
            reduction=reduction,
            get_not_nans=get_not_nans,
        )

# %% ../nbs/060_metrics.ipynb #c8d22398
class FRCMetric(BioMetric):
    """
    Compute the Fourier Ring Correlation metric.

    The metric uses ``FRCLoss`` through MONAI's ``LossMetric`` wrapper.
    """

    _default = _FRCLossMetric

# %% ../nbs/060_metrics.ipynb #ba352fcc
class VarianceMetric(BioMetric):
    _default = mm.VarianceMetric

# %% ../nbs/060_metrics.ipynb #4536906b
class LabelQualityScore(BioMetric):
    _default = mm.LabelQualityScore
