"""Core data structures and classes for biomedical imaging, integrating MONAI's MetaTensors with fastai's transform pipelines."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/021_data.core.ipynb.

# %% auto #0
__all__ = ['BIOCATEGORIZE_BACKENDS', 'MetaResolver', 'BioDataClass', 'BioImageBase', 'BioImage', 'BioVolume', 'BioMIP',
           'BioVideo', 'BioMultiChannel', 'BioCategorize', 'BioLabel']

# %% ../../nbs/021_data.core.ipynb #7a8886ba
# =================================
# Standard library
# =================================
from numpy import ndarray
from plum import dispatch

# =================================
# fastai
# =================================
from fastai.torch_core import TensorImage, TensorCategory, TensorMultiCategory
from fastai.vision.all import TransformBlock, Categorize

# =================================
# bonsai
# =================================
from ..utils import *
from ..io import image_reader, image_reader_dict
from ..visualize import show_biodata, show_multichannel

# =================================
# fasttransform patch
# =================================
import fasttransform

_original_repr = fasttransform.transform.Transform.__repr__

def _safe_repr(self):
    try:
        return _original_repr(self)
    except AttributeError as e:
        if "'_BoundFunction' object has no attribute 'methods'" in str(e):
            return f"{self.__class__.__name__}(...)"
        raise

fasttransform.transform.Transform.__repr__ = _safe_repr

# %% ../../nbs/021_data.core.ipynb #4faea311
class MetaResolver(type(torchTensor), metaclass=BypassNewMeta):
    """
    The `MetaResolver` class addresses metaclass conflicts, ensuring compatibility across different data structures. This is particularly useful when integrating with libraries that have specific metaclass requirements.
    """
    pass
    

# %% ../../nbs/021_data.core.ipynb #95565a2c
class BioDataClass(MetaTensor):
    """
    Base class for bonsai data.
    """

    _transforms = None
    _keys = []

    # --------------------------------------------------
    # BASIC CONSTRUCTORS
    # --------------------------------------------------
    @classmethod
    def from_tensor(cls, x: torchTensor, meta: dict | None = None):
        return cls(x=x, meta=meta or {})
    
    @classmethod
    def from_metatensor(cls, x: MetaTensor):
        return cls(x=x.data, meta=x.meta)

    @classmethod
    def from_numpy(cls, x: ndarray, meta: dict | None = None):
        return cls(x=x, meta=meta or {})
    
    # --------------------------------------------------
    # TRANSFORMS
    # --------------------------------------------------
    @classmethod
    def set_transforms(cls, transforms):
        cls._transforms = transforms
    
    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def from_source(cls, x, **kwargs):
        raise NotImplementedError("Subclasses must implement the `create` method to define how to instantiate from raw data.")
    
    @classmethod
    def from_dict(cls, x:dict, keys:str|Iterable[str]=None, **kwargs):
        raise NotImplementedError("Subclasses must implement the `create` method to define how to instantiate from raw data.")
    
    # --------------------------------------------------
    # CREATE DATABLOCK (fastai integration)
    # --------------------------------------------------
    @classmethod
    def get_datablock(cls):
        return TransformBlock(type_tfms=[cls.from_source])

    # --------------------------------------------------
    # REPR
    # --------------------------------------------------
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}{self.as_tensor().__repr__()[6:]}"

# %% ../../nbs/021_data.core.ipynb #c04e0a04
class BioImageBase(BioDataClass, TensorImage, metaclass=MetaResolver):
    """
    Base class for bioimaging data.

    Provides:
    - MetaTensor integration
    - visualization utilities
    - lightweight tensor wrapper

    """

    _bypass_type = torchTensor
    _show_args = {"cmap": "gray"}
    _channels = "CZYX"
    _output = 'metatensor'
    _transforms = None
    _keys = ['image']

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def from_source(cls, x, **kwargs):
        metatensor = cls.get_loader(**kwargs)(x)
        return cls(metatensor.data, meta=metatensor.meta)
    
    @classmethod
    def from_dict(cls, x:dict, keys:str|Iterable[str]=None, **kwargs):
        if keys is None:
            keys = []

        metatensor_dict = cls.get_dict_loader(keys=keys, **kwargs)(x)

        if isinstance(keys, str):
            keys = [keys]

        for key in keys:
            if key in metatensor_dict:
                x = metatensor_dict[key]
                metatensor_dict[key] = cls(x.data, meta=x.meta)

        return metatensor_dict
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def get_loader(cls,**kwargs) -> Callable:
        def _load(x):
            if isinstance(x, torchTensor):
                return cls.from_tensor(x)

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("output", cls._output)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader(
                x,
                **local_kwargs,
            )

        return _load

    @classmethod
    def get_dict_loader(cls, **kwargs) -> Callable:
        def _load_dict(data: dict):

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("keys", cls._keys)
            local_kwargs.setdefault("output", cls._output)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader_dict(
                data,
                **local_kwargs,
            )

        return _load_dict
    
    # --------------------------------------------------
    # VISUALIZATION
    # --------------------------------------------------
    def show(self, ctx=None, figsize=None, title=None, **kwargs):
        return show_biodata(
            self,
            ctx=ctx,
            title=title if title is not None else None,
            volume_mode='grid',
            figsize=figsize,
            **merge(self._show_args, kwargs),
        )
    

# %% ../../nbs/021_data.core.ipynb #bcec9658
class BioImage(BioImageBase):
    """
    Tensor-backed bioimage loaded from disk.
    """

    _channels = "CYX"


# %% ../../nbs/021_data.core.ipynb #a32aa47a
class BioVolume(BioImageBase):
    """
    Tensor-backed volume loaded from disk.

    """

    _channels="CZYX"


# %% ../../nbs/021_data.core.ipynb #b6cdac7d
def _mip_transform(cls, img, layout):
    z_dim = layout.index("Z")

    mip = torchmax(img.as_tensor(), dim=z_dim).values

    meta = dict(img.meta)
    meta["layout"] = layout.replace("Z", "")
    meta["size_output"] = tuple(mip.shape)

    return cls(x=mip, meta=meta)

# %% ../../nbs/021_data.core.ipynb #4ebea767
class BioMIP(BioImageBase):
    """
    The `BioMIP` class represents a 3D image stack as a 2D image using maximum intensity projection. This is particularly useful for visualizing volumetric data in a 2D format, aiding in quick assessments and presentations.
    """
    
    _show_args = {"cmap": "gray"}
    _channels = "CZYX"
    _channel_modes = {1: "L", 3: "RGB", 4: "RGBA"}

    @classmethod
    def _get_layout(cls, img, kwargs):
        return img.meta.get("layout") or kwargs.get("channels") or cls._channels

    @classmethod
    def from_source(cls, x, keys=None, **kwargs):
        kwargs.setdefault("channels", cls._channels)

        is_dict_input = isinstance(x, dict) or (
            isinstance(x, Sequence)
            and x
            and isinstance(x[0], dict)
        )

        if is_dict_input:
            out = super(cls, cls).from_source(
                x,
                keys=keys,
                **kwargs,
            )

            if keys is None:
                keys = []

            if isinstance(keys, str):
                keys = [keys]

            layout = kwargs.get("channels")

            for key in keys:
                img = out[key]
                out[key] = _mip_transform(cls, img, layout)

            return out

        img = super(cls, cls).from_source(x, **kwargs)

        layout = kwargs.get("channels")

        return _mip_transform(cls, img, layout)


# %% ../../nbs/021_data.core.ipynb #0febd1d1
class BioVideo(BioImageBase):
    """
    Tensor-backed video loaded from disk.

    This is the class that:
    - uses image_reader
    - handles transforms
    - returns MetaTensor-backed images
    """

    _channels="CTYX"
    

# %% ../../nbs/021_data.core.ipynb #b484acfa
class BioMultiChannel(BioImageBase):
    """
    Multi-channel 2D/3D image assuming CZYX layout.
    """

    @classmethod
    def _apply_mip(cls, tensor, merge_cd, interleaved, **kwargs):
            layout = (
                kwargs.get("layout")
                or getattr(tensor, "meta", {}).get("layout")
                or cls._channels
            )

            if not merge_cd:
                if hasattr(tensor, "meta"):
                    tensor.meta["layout"] = layout
                    tensor.meta["size_output"] = tuple(tensor.shape)
                return tensor

            if layout is None or "C" not in layout or "Z" not in layout:
                raise ValueError(
                    f"BioMultiChannel merge_cd requires C and Z axes, got {layout!r}"
                )

            c_dim = layout.index("C")
            z_dim = layout.index("Z")

            c = tensor.shape[c_dim]
            d = tensor.shape[z_dim]

            spatial_dims = [i for i in range(tensor.ndim) if i not in (c_dim, z_dim)]

            if interleaved:
                permute_dims = [z_dim, c_dim, *spatial_dims]
            else:
                permute_dims = [c_dim, z_dim, *spatial_dims]

            tensor = tensor.permute(*permute_dims)
            tensor = tensor.reshape(c * d, *tensor.shape[2:])

            output_layout = layout.replace("Z", "")

            if hasattr(tensor, "meta"):
                tensor.meta["layout"] = output_layout
                tensor.meta["size_output"] = tuple(tensor.shape)

            return tensor
    
    @classmethod
    def from_source(
        cls,
        x: PathLike | Sequence[PathLike] | torchTensor,
        keys=None,
        merge_cd: bool = True,
        interleaved: bool = True,
        **kwargs,
    ):
        kwargs.setdefault("channels", cls._channels)

        out = super().from_source(x, keys=keys, **kwargs)

        if isinstance(out, dict):
            return {k: cls._apply_mip(v, merge_cd=merge_cd, interleaved=interleaved, **kwargs) for k, v in out.items()}

        return cls._apply_mip(out, merge_cd=merge_cd, interleaved=interleaved, **kwargs)

    def show(self, ctx=None, **kwargs):
        return show_multichannel(self, ctx=ctx, **merge(self._show_args, kwargs))



# %% ../../nbs/021_data.core.ipynb #381f0392
def _to_fastai(x):
    return x

def _to_monai(x):
    return x.as_subclass(torchTensor)

def _to_numpy(x):
    return x.cpu().numpy()


BIOCATEGORIZE_BACKENDS = {
    "fastai": _to_fastai,
    "monai": _to_monai,
    "torch": _to_monai,
    "ignite": _to_monai,
    "keras": _to_monai,
    "numpy": _to_numpy,
    # "tensorflow": _to_numpy,
    # "jax": _to_numpy,
}


class BioCategorize(DisplayedTransform):
    """Encode categorical labels using fastai's ``Categorize`` transform.

    Supports fastai tensors, PyTorch tensors, or NumPy arrays.

    Args:
        vocab: Optional label vocabulary.
        sort: Whether to sort the vocabulary.
        add_na: Whether to include an unknown-category label.
        backend: Output backend.
    """

    def __init__(
        self,
        vocab=None,
        sort=True,
        add_na=False,
        backend="monai",
    ):
        if backend not in BIOCATEGORIZE_BACKENDS:
            raise ValueError(
                f"BioCategorize: unknown backend {backend!r}. "
                f"Expected one of {set(BIOCATEGORIZE_BACKENDS)}."
            )

        self.cat = Categorize(
            vocab=vocab,
            sort=sort,
            add_na=add_na,
        )
        self.backend = backend

    @property
    def vocab(self):
        return self.cat.vocab

    @property
    def sort(self):
        return self.cat.sort

    @property
    def add_na(self):
        return self.cat.add_na

    @property
    def c(self):
        return self.cat.c

    def encodes(self, o):
        x = self.cat(o)
        return BIOCATEGORIZE_BACKENDS[self.backend](x)

    def decodes(self, o):
        return self.cat.decode(o)

# %% ../../nbs/021_data.core.ipynb #d3ec8d1a
class BioLabel(BioDataClass):
    """
    Data class for categorical target labels.

    This class defines how labels are encoded/decoded for tasks involving
    categorical values, including optional vocabulary sorting and NA handling.
    """

    _keys = ["label"]
    _vocab = None
    _sort = True
    _add_na = False
    _backend = "monai"

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------

    @classmethod
    def from_source(cls, x, **kwargs):
        """Load a label from a raw source using the configured encoder."""
        cat = cls.get_label(**kwargs)
        return cat(x)

    @classmethod
    def from_dict(
        cls,
        x: dict,
        keys: str | Iterable[str] = None,
        **kwargs,
    ):
        """Load categorical labels from one or more keys in a dictionary."""
        cat = cls.get_dict_label(keys=keys, **kwargs)
        return cat(x)

    # --------------------------------------------------
    # ENCODING
    # --------------------------------------------------

    @classmethod
    def _get_encoder(
        cls,
        vocab=None,
        sort=None,
        add_na=None,
        backend="monai",
    ):
        """Create a categorical encoder configured for this label type."""
        vocab = cls._vocab if vocab is None else vocab
        sort = cls._sort if sort is None else sort
        add_na = cls._add_na if add_na is None else add_na

        return BioCategorize(
            vocab=vocab,
            sort=sort,
            add_na=add_na,
            backend=backend,
        )

    # --------------------------------------------------
    # LABEL
    # --------------------------------------------------

    @classmethod
    def get_label(cls, **kwargs) -> Callable:
        """Return a label encoder configured from class or runtime options."""
        return cls._get_encoder(
            vocab=kwargs.get("vocab", cls._vocab),
            sort=kwargs.get("sort", cls._sort),
            add_na=kwargs.get("add_na", cls._add_na),
            backend=kwargs.get("backend", cls._backend),
        )

    # --------------------------------------------------
    # DICT LABEL
    # --------------------------------------------------

    @classmethod
    def get_dict_label(cls, **kwargs) -> Callable:
        """Return a loader that encodes selected categorical fields in a dict."""
        keys = kwargs.get("keys", cls._keys)

        if isinstance(keys, str):
            keys = [keys]

        cat = cls._get_encoder(
            vocab=kwargs.get("vocab", cls._vocab),
            sort=kwargs.get("sort", cls._sort),
            add_na=kwargs.get("add_na", cls._add_na),
            backend=kwargs.get("backend", cls._backend),
        )

        def _load_dict(data: dict):
            """Encode one or more categorical fields in a dictionary."""
            out = data.copy()

            for key in keys:
                out[key] = cat(data[key])

            return out

        # Keep useful metadata on the loader
        _load_dict.vocab = cat.vocab
        _load_dict.sort = cat.sort
        _load_dict.add_na = cat.add_na
        _load_dict.keys = keys
        _load_dict.cat = cat
        _load_dict.backend = cat.backend

        return _load_dict
